### ISSUE TITLE
Number of slots bugged after upgrading to diamond backpack

### ISSUE THREAD

**Issue by asoshinsky** [Flanks255/simplybackpacks#43]
I upgraded the basic to diamond backpack and I am experiencing a weird bug where it seems like it can hold much fewer items then visible 66 slots. If I try to put more than 17 items it starts spitting them out or putting them back to inventory as soon as I close the backpack... As if it was a common backpack, not a diamond. 

**Screenshots**
Diamond backpack before putting desired items into:
![image](https://user-images.githubusercontent.com/60367873/147299917-64131a13-9a07-4aea-905c-5c5e4c5262fe.png)

Shift+right clicking/transferring items to the backpack:
![image](https://user-images.githubusercontent.com/60367873/147300049-591cf44a-7fe5-458c-8799-af027c34f005.png)

Closing inventory by pressing E or Esc and reopening the backpack:
![image](https://user-images.githubusercontent.com/60367873/147300118-2660c0bd-f9bb-4f72-aaba-b008ebdafe24.png)

Very weird behaviour.

Forge: 36.2.20
simplybackpacks-1.16.5-2.0.0-build.18
Modpack: Oceanblock version 1.11.0

**Comment by Flanks255** [comment]
try updating the mod to 2.0.1? might be related to the bug i fixed in that version.

**Comment by craftycowcat** [comment]
I am experiencing the same bug, but I upgraded from uncommon to rare. It seems that I can only use half the slots of the intended 66. I already upgraded to the version you suggested above.

**Comment by Flanks255** [comment]
Single or multiplayer? Can you attach the backpack datafile from the
save/data folder.

**Comment by craftycowcat** [comment]
Singleplayer. I already cheated a brand new backpack in. But it is easy to recreate:
- Craft a common backpack
- Craft an uncommon backpack
- Craft a rare backpack

When you grab a backpack from creative (or grab one from a chest in Ocean Block) it acts how it's supposed to.

**update:** _I think I updated between making the backpacks. I made a new one the way I described above and I can put all the items in again. Working as intended (for me)._

**Comment by Flanks255** [comment]
my guess is it was related to the previous bug fixed in 2.0.1, perhaps if the backpack was crafted, opened and used, then upgraded without opening and the mod got updated. if everyone is working ok ill close this.

**Comment by koukimonster91** [comment]
i had the same issue, came here, found this. i updated the mod and it fixed the issue. when i first tried it after updating the bag wasnt fixed, i had the same issue. i made a new bag and i was unable to even open it using a hotkey. i stuck the new one on my hotbar then right clicked to open it and it opened that way and it was able to be opened using the hotkey after that. i then did the same thing to the one built in the previous version that was still bugged and it fixed it aswell.

**Comment by Flanks255** [comment]
so opening the backpack normally via right clicking solved it? (im guessing you always opened it via hotkey before?)

**Comment by koukimonster91** [comment]
that is correct on both accords

**Comment by Flanks255** [comment]
ok, i guess i should make it do the upgrade check on hotkey open as well(atm it only does migration/upgrade checks on right click opening)

**Comment by Flanks255** [comment]
Fixed in 2.0.2 in 1.16 / 1.18
